---
- name: create users
  hosts: all
  tasks:
          - name: create users
            become: true
            ansible.builtin.user:
                    name: "{{item}}"
            loop:
                    - joe
                    - sam 


