---
- name: conditional and loops exercise
  hosts: client1.tshoot.com
  vars:
          mariadb_packages:
                  - mariadb-server
                  - python3-PyMySQL
  tasks:
          - name: install maria
            become: true
            ansible.builtin.dnf:
                    name: "{{ item }}"
                    state: present
            loop: "{{ mariadb_packages }}"
            when: ansible_facts['distribution']== "RedHat"
          
          - name: start mariadb service
            become: true
            ansible.builtin.service:
                    name: mariadb
                    state: started
                    enabled: true



