---
- name: Configure SOE
  hosts: all
  become: true
  vars:
          system_owner: cluddfsdsaf@sfda.com
  tasks:
          - name: sdsadsa
            ansible.builtin.template:
                    src: motd.j2
                    dest: /etc/motd
                    owner: root
                    group: root
                    mode: 0644

                    


