---
- name: repos
  hosts: all
  vars:
          custom_pkg: simple-agent

  tasks:
          - name: gather info about installed packages
            ansible.builtin.package_facts:
                    manager: auto

          - name: display value of 1st task          
            ansible.builtin.debug:
                    var: ansible_facts[packages][custom_pkg]
            when: custom_pkg in ansible_facts[packages] 





          - name: ensure example repo exists
            ansible.builtin.yum_repository:
                    file: /etc/yum.repos.d/example
                    baseurl: http://materials.example.com/yum/repository/
                    gpgcheck: true
                    description: : Example Inc. Internal YUM repo
                    name: example-internal

          - name: ensure RPM key is installed
            ansible.builtin.rpm_key:
                    key:  http://materials.example.com/yum/repository/RPM-GPG-KEY-example
                    state: present

          - name: install package
            ansible.builtin.dnf:
                    name: "{{custom_pkg}}"
                    state: present

                    

