---
- name: Change default boot target
  hosts: client3.tshoot.com
  become: true
  gather_facts: false
  vars:
      default_target: "graphical.target"
  tasks:
          - name: get cuurent boot target
            ansible.builtin.command:
                    cmd: systemctl get-default
            changed_when: false        
            register: target

          - name: change target
            ansible.builtin.command:
                    cmd: systemctl set-default {{ default_target }}
            when: default_target not in target['stdout']        

