---
- name: network config
  hosts: all
  roles:
          - name: redhat.rhel_system_roles.network
            network_connections:
                    - name: eth0
                      type: ethernet
                      ip:
                              address: 172.25.250.30/24

