---
- name: repo config
  hosts: client3.tshoot.com
  tasks:
          - name: ensure repo exists
            ansible.builtin.yum_repository:
                    name: Example-internal
                    descrtiption:  Example Inc. Internal YUM repo
                    file: example
                    baseurl: http://materials.example.com/yum/repository
                    gpgcheck: true


          - name: ensure RPM key is installed
            ansible.builtin.rpm_key:
                    key:  http://materials.example.com/yum/repository/RPM-GPG-KEY-example
                    state: present
                    
          - name: install rhelever package
            ansible.builtin.dnf:
                    name: rhelever
                    state: present
                        
