---
# tasks file for myvhost
- name: install  httpd
  become: true
  ansible.builtin.dnf:
          name: httpd
          state: latest

- name: enable httpd
  become: true
  ansible.builtin.service:
          name: httpd
          state: started
          enabled: true
   
- name: vhost is installed
  become: true
  ansible.builtin.template:
          src: vhost.conf.j2
          dest: /etc/httpd/conf.d/vhost.conf
          owner: root
          group: root
          mode: 0644
  notify:
          - restart httpd       
